<template>
  <div>
    <div>동적 파라미터(#{...}) 를 분석해서 MyBatis 동적 SQL 생성. SQL 예제</div>
    <codemirror v-model="sqlCode" :options="sqlOptions" />
    <div style="margin-buttom:10px,margin-top:10px">
      <span style="color:red">동적 파라미터는 quotation으로 구분</span>. 생성된 Mapper xml 예제
    </div>
    <codemirror v-model="xmlCode" :options="xmlOptions" />
  </div>
</template>
<script>
export default {
  data() {
    return {
      sqlOptions: {
        readOnly: true,
        tabSize: 4,
        styleActiveLine: true,
        lineNumbers: true,
        line: true,
        mode: "text/x-mysql",
        theme: "solarized light",
      },
      xmlOptions: {
        readOnly: true,
        tabSize: 4,
        styleActiveLine: true,
        lineNumbers: true,
        line: true,
        mode: "application/xml",
        theme: "solarized light",
      },
      sqlCode: "",
      xmlCode: "",
    };
  },
  mounted: function () {
    this.sqlCode =
      "SELECT \n" +
      "    *\n" +
      "FROM\n" +
      "    t_order t\n" +
      "        LEFT JOIN\n" +
      "    t_order_good t1 ON t.id = t1.order_id\n" +
      "WHERE\n" +
      "    t.order_code = '#{orderCode}'\n" +
      "        AND t.city LIKE '#{city}'\n" +
      "        AND t.customer_id IN '#{customerIds}'\n" +
      "        AND t.creator = '#{creator}'\n" +
      "        AND t.confirm_time BETWEEN '#{startTime}' AND '#{endTime}'";
    this.xmlCode =
      "<!--Author:david，Date:2020-07-14, auto-generated by mybatis-plus-generator-ui -->\n" +
      '  <select id="selectOrders" resultMap="ExampleDtoMap"> <![CDATA[\n' +
      "      SELECT \n" +
      "          *\n" +
      "      FROM\n" +
      "          t_order t\n" +
      "              LEFT JOIN\n" +
      "          t_order_good t1 ON t.id = t1.order_id\n" +
      "      WHERE\n" +
      "           1=1 \n" +
      '      <if test="orderCode!=null">\n' +
      "        AND  order_code = #{orderCode}\n" +
      "      </if>\n" +
      '      <if test="city!=null">\n' +
      "       AND city like concat('%',#{city},'%')\n" +
      "      </if>\n" +
      '      <if test="customerIds!=null">\n' +
      "       AND customer_id in \n" +
      '       <foreach item="item" collection="#{customerIds}" open="(" separator="," close=")">\n' +
      "       #{item}\n" +
      "       </foreach>\n" +
      "      </if>\n" +
      '      <if test="creator!=null">\n' +
      "       AND creator = #{creator}\n" +
      "      </if>\n" +
      '      <if test="startTime!=null">\n' +
      "       AND confirm_time between #{startTime} and #{endTime}\n" +
      "      </if>\n" +
      "    ]]>\n" +
      "  </select>";
  },
  methods: {},
};
</script>
